import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    ".next-e2e/**",
    ".e2e/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the shadcn / AI Elements registries; updated with `npx shadcn add`, not hand-edited.
    "components/ui/**",
    "components/ai-elements/**",
    "hooks/use-mobile.ts",
  ]),
]);

export default eslintConfig;
